# -*- mode: toml -*-
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
"$schema" = "https://pixi.sh/v0.59.0/schema/manifest/schema.json"

[workspace]
name = "trexio-feedstock"
version = "2026.9.23"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/trexio-feedstock"
authors = ["@conda-forge/trexio"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
requires-pixi = ">=0.59.0"

[tasks.build-locally]
cmd = "pixi exec --force-reinstall --list='^python$' python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[tasks.smithy]
cmd = "pixi exec --force-reinstall --list='^conda-smithy$' conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[tasks.rerender]
cmd = "pixi exec --force-reinstall --list='^conda-smithy$' conda-smithy rerender"
description = "Rerender the feedstock."

[tasks.lint]
cmd = "pixi exec --list='^conda-smithy$' conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[feature.build.dependencies]
conda-build = ">=26.3"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[feature.build.tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[feature.build.tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build trexio-feedstock directly (without setup scripts), no particular variant specified"
[feature.build.tasks."build-linux_64_mpimpich"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_mpimpich.yaml --target-platform linux-64"
description = "Build trexio-feedstock with variant linux_64_mpimpich directly (without setup scripts)"
[feature.build.tasks."debug-linux_64_mpimpich"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_64_mpimpich.yaml --target-platform linux-64"
description = "Debug trexio-feedstock with variant linux_64_mpimpich directly (without setup scripts)"
[feature.build.tasks."inspect-linux_64_mpimpich"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_mpimpich.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_64_mpimpich"
[feature.build.tasks."build-linux_64_mpinompi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_mpinompi.yaml --target-platform linux-64"
description = "Build trexio-feedstock with variant linux_64_mpinompi directly (without setup scripts)"
[feature.build.tasks."debug-linux_64_mpinompi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_64_mpinompi.yaml --target-platform linux-64"
description = "Debug trexio-feedstock with variant linux_64_mpinompi directly (without setup scripts)"
[feature.build.tasks."inspect-linux_64_mpinompi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_mpinompi.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_64_mpinompi"
[feature.build.tasks."build-linux_64_mpiopenmpi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_mpiopenmpi.yaml --target-platform linux-64"
description = "Build trexio-feedstock with variant linux_64_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."debug-linux_64_mpiopenmpi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_64_mpiopenmpi.yaml --target-platform linux-64"
description = "Debug trexio-feedstock with variant linux_64_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."inspect-linux_64_mpiopenmpi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_mpiopenmpi.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_64_mpiopenmpi"
[feature.build.tasks."build-linux_aarch64_mpimpich"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_mpimpich.yaml --target-platform linux-aarch64"
description = "Build trexio-feedstock with variant linux_aarch64_mpimpich directly (without setup scripts)"
[feature.build.tasks."debug-linux_aarch64_mpimpich"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_aarch64_mpimpich.yaml --target-platform linux-aarch64"
description = "Debug trexio-feedstock with variant linux_aarch64_mpimpich directly (without setup scripts)"
[feature.build.tasks."inspect-linux_aarch64_mpimpich"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_mpimpich.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_aarch64_mpimpich"
[feature.build.tasks."build-linux_aarch64_mpinompi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_mpinompi.yaml --target-platform linux-aarch64"
description = "Build trexio-feedstock with variant linux_aarch64_mpinompi directly (without setup scripts)"
[feature.build.tasks."debug-linux_aarch64_mpinompi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_aarch64_mpinompi.yaml --target-platform linux-aarch64"
description = "Debug trexio-feedstock with variant linux_aarch64_mpinompi directly (without setup scripts)"
[feature.build.tasks."inspect-linux_aarch64_mpinompi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_mpinompi.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_aarch64_mpinompi"
[feature.build.tasks."build-linux_aarch64_mpiopenmpi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_mpiopenmpi.yaml --target-platform linux-aarch64"
description = "Build trexio-feedstock with variant linux_aarch64_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."debug-linux_aarch64_mpiopenmpi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_aarch64_mpiopenmpi.yaml --target-platform linux-aarch64"
description = "Debug trexio-feedstock with variant linux_aarch64_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."inspect-linux_aarch64_mpiopenmpi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_mpiopenmpi.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_aarch64_mpiopenmpi"
[feature.build.tasks."build-linux_ppc64le_mpimpich"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_mpimpich.yaml --target-platform linux-ppc64le"
description = "Build trexio-feedstock with variant linux_ppc64le_mpimpich directly (without setup scripts)"
[feature.build.tasks."debug-linux_ppc64le_mpimpich"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_ppc64le_mpimpich.yaml --target-platform linux-ppc64le"
description = "Debug trexio-feedstock with variant linux_ppc64le_mpimpich directly (without setup scripts)"
[feature.build.tasks."inspect-linux_ppc64le_mpimpich"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_mpimpich.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_ppc64le_mpimpich"
[feature.build.tasks."build-linux_ppc64le_mpinompi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_mpinompi.yaml --target-platform linux-ppc64le"
description = "Build trexio-feedstock with variant linux_ppc64le_mpinompi directly (without setup scripts)"
[feature.build.tasks."debug-linux_ppc64le_mpinompi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_ppc64le_mpinompi.yaml --target-platform linux-ppc64le"
description = "Debug trexio-feedstock with variant linux_ppc64le_mpinompi directly (without setup scripts)"
[feature.build.tasks."inspect-linux_ppc64le_mpinompi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_mpinompi.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_ppc64le_mpinompi"
[feature.build.tasks."build-linux_ppc64le_mpiopenmpi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_mpiopenmpi.yaml --target-platform linux-ppc64le"
description = "Build trexio-feedstock with variant linux_ppc64le_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."debug-linux_ppc64le_mpiopenmpi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_ppc64le_mpiopenmpi.yaml --target-platform linux-ppc64le"
description = "Debug trexio-feedstock with variant linux_ppc64le_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."inspect-linux_ppc64le_mpiopenmpi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_mpiopenmpi.yaml"
description = "List contents of trexio-feedstock packages built for variant linux_ppc64le_mpiopenmpi"
[feature.build.tasks."build-osx_64_mpimpich"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_mpimpich.yaml --target-platform osx-64"
description = "Build trexio-feedstock with variant osx_64_mpimpich directly (without setup scripts)"
[feature.build.tasks."debug-osx_64_mpimpich"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/osx_64_mpimpich.yaml --target-platform osx-64"
description = "Debug trexio-feedstock with variant osx_64_mpimpich directly (without setup scripts)"
[feature.build.tasks."inspect-osx_64_mpimpich"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_mpimpich.yaml"
description = "List contents of trexio-feedstock packages built for variant osx_64_mpimpich"
[feature.build.tasks."build-osx_64_mpinompi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_mpinompi.yaml --target-platform osx-64"
description = "Build trexio-feedstock with variant osx_64_mpinompi directly (without setup scripts)"
[feature.build.tasks."debug-osx_64_mpinompi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/osx_64_mpinompi.yaml --target-platform osx-64"
description = "Debug trexio-feedstock with variant osx_64_mpinompi directly (without setup scripts)"
[feature.build.tasks."inspect-osx_64_mpinompi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_mpinompi.yaml"
description = "List contents of trexio-feedstock packages built for variant osx_64_mpinompi"
[feature.build.tasks."build-osx_64_mpiopenmpi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_mpiopenmpi.yaml --target-platform osx-64"
description = "Build trexio-feedstock with variant osx_64_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."debug-osx_64_mpiopenmpi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/osx_64_mpiopenmpi.yaml --target-platform osx-64"
description = "Debug trexio-feedstock with variant osx_64_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."inspect-osx_64_mpiopenmpi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_mpiopenmpi.yaml"
description = "List contents of trexio-feedstock packages built for variant osx_64_mpiopenmpi"
[feature.build.tasks."build-osx_arm64_mpimpich"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_mpimpich.yaml --target-platform osx-arm64"
description = "Build trexio-feedstock with variant osx_arm64_mpimpich directly (without setup scripts)"
[feature.build.tasks."debug-osx_arm64_mpimpich"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/osx_arm64_mpimpich.yaml --target-platform osx-arm64"
description = "Debug trexio-feedstock with variant osx_arm64_mpimpich directly (without setup scripts)"
[feature.build.tasks."inspect-osx_arm64_mpimpich"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_mpimpich.yaml"
description = "List contents of trexio-feedstock packages built for variant osx_arm64_mpimpich"
[feature.build.tasks."build-osx_arm64_mpinompi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_mpinompi.yaml --target-platform osx-arm64"
description = "Build trexio-feedstock with variant osx_arm64_mpinompi directly (without setup scripts)"
[feature.build.tasks."debug-osx_arm64_mpinompi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/osx_arm64_mpinompi.yaml --target-platform osx-arm64"
description = "Debug trexio-feedstock with variant osx_arm64_mpinompi directly (without setup scripts)"
[feature.build.tasks."inspect-osx_arm64_mpinompi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_mpinompi.yaml"
description = "List contents of trexio-feedstock packages built for variant osx_arm64_mpinompi"
[feature.build.tasks."build-osx_arm64_mpiopenmpi"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_mpiopenmpi.yaml --target-platform osx-arm64"
description = "Build trexio-feedstock with variant osx_arm64_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."debug-osx_arm64_mpiopenmpi"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/osx_arm64_mpiopenmpi.yaml --target-platform osx-arm64"
description = "Debug trexio-feedstock with variant osx_arm64_mpiopenmpi directly (without setup scripts)"
[feature.build.tasks."inspect-osx_arm64_mpiopenmpi"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_mpiopenmpi.yaml"
description = "List contents of trexio-feedstock packages built for variant osx_arm64_mpiopenmpi"

[environments]
build = ["build"]
# This is a copy of 'build', to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = ["build"]
